/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;

/**
 *
 * @author JenifferHR
 */
public class Panel_Botones extends javax.swing.JPanel {
    
    public Panel_Botones() {
        initComponents();
    }
    
    public void recibirControlador(ActionListener controlador)
     {
       jB_Agregar.addActionListener(controlador);
       jB_Modificar.addActionListener(controlador);
       jB_Consultar.addActionListener(controlador);
       jB_Eliminar.addActionListener(controlador);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Consultar = new javax.swing.JButton();
        jB_Agregar = new javax.swing.JButton();
        jB_Modificar = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();

        jB_Consultar.setText("Consultar");

        jB_Agregar.setText("Agregar");

        jB_Modificar.setText("Modificar");

        jB_Eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jB_Consultar)
                .addGap(12, 12, 12)
                .addComponent(jB_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Eliminar)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Consultar)
                    .addComponent(jB_Agregar)
                    .addComponent(jB_Modificar)
                    .addComponent(jB_Eliminar))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Agregar;
    private javax.swing.JButton jB_Consultar;
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_Modificar;
    // End of variables declaration//GEN-END:variables
}
